Us004 load events
ONSdigital/rm-tools pull request #6
Opened 2018-01-16 18:10 UTC by madeye-matt

Added a loader script for loading collection exercise events and added test data received from Lou

2018-01-22 13:22 UTC, andrewmil requested changes
We should probably also update `collex-loader/Readme.md` It's not totally obvious how to run it/if it needs to be run separately/together with `load.py`

2018-01-22 14:24 UTC, madeye-matt commented
@andrewmil README.md updated as requested

2018-01-22 15:24 UTC, andrewmil commented on collex-loader/load_events.py
> +    // WATCH OUT: this removes the last : from a valid ISO8601 date string to form another
Wrong way to comment in python

2018-01-22 15:41 UTC, tej99 approved these changes
LG 👍

2018-01-23 17:30 UTC, madeye-matt commented on collex-loader/load_events.py
> +    // WATCH OUT: this removes the last : from a valid ISO8601 date string to form another
Ooops! *looks shifty* fixed now

2018-01-24 10:30 UTC, andrewmil approved these changes

2018-01-24 10:36 UTC, merged

2018-01-24 15:25 UTC, benjefferies commented
We will need to update the Makefile in https://github.com/ONSdigital/ras-integration-tests too